### ISSUE TITLE
Touchscreen improvements

### ISSUE THREAD

**Issue by OgelGames** [mt-mods/digistuff#21]
I've decided to (finally) start on rewriting the `digistuff:touchscreen` code, and thought it would be good to open discussion about what improvements there will be. (also it serves as a goal list and motivation for me ;D)

**Improvements**
* [ ] Add as many missing formspec elements as possible.
* [x] Make it possible to remove or replace individual formspec elements. (using some kind of ID)
* [x] Allow changing formspec size.
* [x] Allow changing background. (default blank)
* [x] ~~Add option for setting `formspec_version`.~~

**Possible additions**
* [x] ~~Make it possible to add users for a locked touchscreen. (like shared chest, but via digiline command)~~
* [x] ~~Allow changing position of formspec. (not sure if this would even be useful)~~

**Code changes**
* [x] Fill missing or invalid values with default values
* [x] Completely change how formspec elements are added, and make it easy to add future elements.
* [x] Store formspec data as a single table of strings instead of tables of values (more efficient for storing in node metadata)

@BuckarooBanzay @S-S-X @SwissalpS @dennisjenkins75 @FeXoR-o-Illuria

**Comment by S-S-X** [comment]
> Make it possible to add users for a locked touchscreen. (like shared chest, but via digiline command)

I think this is not really needed because it is very simple to implement in lua controller.
It does however allow a little bit faster processing but still feels like unnecessary micro optimization that just increases complexity without actually adding anything.
