### ISSUE TITLE
image buttons used to set image with 'image' field now it's 'texture_name'

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/digistuff#33]
image buttons used to set image with 'image' field now it's 'texture_name'

I didn't check which other image elements were available before. Would be nice if all used the same field though.

_Originally posted by @SwissalpS in https://github.com/mt-mods/digistuff/issues/25#issuecomment-1025260314_

Field should be renamed back to image and texture_name removed in my opinion as that gives both better backwards compatibility and stays compatible with original digistuff mod making switching back and forth easier.

**Comment by OgelGames** [comment]
I changed it back to "image", and did the same for every other "texture_name", updating the documentation accordingly.
