### ISSUE TITLE
Touchscreen: modifying label with [ already present causes crash

### ISSUE THREAD

**Issue by Maverick2797** [mt-mods/digistuff#42]
Attempting to `{command = "modify"}` a label (and I suspect other elements too) that have `[` already in them causes a system crash: 

> AsyncErr: Lua: Runtime error from mod '??' in callback environment_Step(): ....8.0-release-win64\bin\..\mods\digistuff\touchscreen.lua:26: attempt to index local 'element' (a nil value)
stack traceback:
	....8.0-release-win64\bin\..\mods\digistuff\touchscreen.lua:26: in function 'modify_element_string'
	....8.0-release-win64\bin\..\mods\digistuff\touchscreen.lua:90: in function 'process_command'
	....8.0-release-win64\bin\..\mods\digistuff\touchscreen.lua:201: in function 'action'
	...t-5.8.0-release-win64\bin\..\mods\digilines/internal.lua:106: in function 'transmit'
	...etest-5.8.0-release-win64\bin\..\mods\digilines\init.lua:60: in function 'receptor_send'
	...n64\bin\..\mods\mesecons\mesecons_luacontroller\init.lua:749: in function <...n64\bin\..\mods\mesecons\mesecons_luacontroller\init.lua:743>
	...ease-win64\bin\..\mods\mesecons\mesecons/actionqueue.lua:137: in function 'execute'
	...ease-win64\bin\..\mods\mesecons\mesecons/actionqueue.lua:111: in function <...ease-win64\bin\..\mods\mesecons\mesecons/actionqueue.lua:73>
	...t-5.8.0-release-win64\bin\..\builtin\common\register.lua:26: in function <...t-5.8.0-release-win64\bin\..\builtin\common\register.lua:12>

I suspect the pattern matching of `touchscreen.lua:21` is returning a nil result, however I am not versed in the black magic of such things enough to debug this.

Simple luacontroller script to reproduce

```
if event.type=="program" then
	local touchscreen_preform = {
		{command = "clear"},
		{command = "add", element = "button", name = "submit", label = "Press Me for crash >:)", X = 5, Y = 2, W = 3, H = 0.8},
		{command = "add", element = "label", label = "innocuous label with pre-existing [", X = 1, Y = 2},
	}
	digiline_send("touch",touchscreen_preform)
	return
end

if event.channel=="touch" and not event.msg.quit then
digiline_send("touch",{command = "modify", index = 2, label = "anything else"})
end
```

**Comment by OgelGames** [comment]
Yeah, the pattern was too greedy :) Fixed in https://github.com/mt-mods/digistuff/commit/0b764757194886c3d88469ed8cb2e7e33fb1fb52
