### ISSUE TITLE
`relmove` is broken when sent to multiple movestones

### ISSUE THREAD

**Issue by Makefile-dot-in** [mt-mods/digistuff#46]
## Description

When a single `relmove` command is sent to multiple movestones sharing a channel, the movestones will move in opposing directions.

## How to reproduce

1. Place a 4x4 (or larger) wall of movestones.
2. Set each movestone to the channel `movs`.
3. Place a luacontroller next to the wall and type in the program `digiline_send("movs", {command = "relmove", <axis> = 50, maxstack = 1})`, where `<axis>` is an axis perpendicular to the wall

## Expected behavior

The movestones move along the chosen axis in parallel.

## Actual behavior

The movestones scatter in different directions.

## Cause

This is caused by the digilines receiver code for movestones mutating the original message, which causes the receiver code for the other movestones to receive the altered message rather than the original.

**Comment by BuckarooBanzay** [comment]
thank you for this very detailed bug-report :+1:
