### ISSUE TITLE
Digistuff movestone won't move

### ISSUE THREAD

**Issue by elettrico** [mt-mods/digistuff#49]
I've a digistuff movestone connected to a vertical digimese column and configured to respond to channel "mov".
Then I've a luacontroller connected to the same digiline, to a button (pin C) and to a light (pin B), with this code:

if (event.type=="on" and event.pin.name=="C") then
  digiline_send("mov", {command="absmove", y=13})
  port.b = true
end

I expect the light to turn on and the digistuff movestone to move up to y=13. the light turn on but the movestone don't move. Inspecting the channel with a LCD shows the signal with the table is being sent correctly.

I suspect a bug, what kind of feedback can I provide?

**Comment by OgelGames** [comment]
You need to set `maxstack = 1`:
```lua
digiline_send("mov", {command = "absmove", y = 13, maxstack = 1})
```
https://github.com/mt-mods/digistuff/blob/71b606c86530fa18016f7cf319d881e5e09bbbf3/docs/movestone.txt#L13

Technically not a bug, but a bad default value. The minimum value for `maxstack` should be 1, not 0.
