### ISSUE TITLE
[bug] Digiline movestone - it can travel the world

### ISSUE THREAD

**Issue by TheEt1234** [mt-mods/digistuff#57]
# Steps to reproduce
1) Have a digiline movestone with the channel ""
2) Have a luacontroller with:
```lua
if event.type == "program" then
  digiline_send("", {
    command = "absmove",
    x = 0,
    sticky = true,
    allsticky = true,
    maxstack = 10
  })
end
```

# debug info
- was tested on pandorabox test server
- getstate output:
```lua
{
	type = "digiline",
	channel = "",
	msg = {
		pos = {
			x = -302,
			y = 97,
			z = 4071
		},
		targetpos = {
			x = -302,
			y = 97,
			z = 4071
		}
	}
}
```

**Comment by SwissalpS** [comment]
so you started at ``-302, 97, 4071``? and where did you end up?

**Comment by TheEt1234** [comment]
> so you started at `-302, 97, 4071`? and where did you end up?

~~it kept moving~~ `oh so turns out i am a dumbo and did not test this propertly, it only goes for like 40~50 nodes`
